services:
  - type: web
    name: safe-haven
    env: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build && cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
